services:
  db:
    image: mariadb
    container_name: prakti-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1qa<YXCV
      MYSQL_DATABASE: prakti
    volumes:
      - ./mysql-data:/var/lib/mysql
